DEBUG=1
SECRET_KEY = "shopper_sna"
UPLOAD_FOLDER = "img/profiler"
PRODIUT_UPLOAD_FOLDER = "img/produits"

HOST = "localhost"
USER_ = "root"
PASSWORD = ""
DATABASE = "gnnyket"

SHOPPER_PROD_NUMBER = 9
SALLES_TABLEAU_NUMBER = 10
SALLES_GRILLE_NUMBER = 8
